[project]
include_dirs = [ "src/" ]     
build_dir    = "_build"    # Définit où sortir les fichiers compilés générés.
target_dir   = "_target"   # Définit où sortir les fichiers finaux des cibles.

# Chaque section [[target]] décrit une cible de construction pour le projet

[[target]]
name     = "deplacement"                       # Le nom de la cible
modules  = [ "Nainwak" ]  # Composants modules
tests    = [ "tests/test_nainwak1.catala_fr" ] # Test(s) associé(s)
backends = [ "ocaml" ]

